controller_list:
  - name: fake_rb1_arm_controller
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
      - j7
  - name: fake_rb1_arm_torso_controller
    joints:
      - j1_torso
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
      - j7
  - name: fake_rb1_gripper_controller
    joints:
      - jg2
  - name: fake_rb1_head_controller
    joints:
      - j1_head
      - j2_head
  - name: fake_rb1_robot_controller
    joints:
      - j1_torso
      - j1_head
      - j2_head
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
      - j7
      - jg2