joint_limits:
  j1:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: false
    max_acceleration: 0
  j3:
    has_velocity_limits: true
    max_velocity: 3.1527
    has_acceleration_limits: false
    max_acceleration: 0
  j1_head:
    has_velocity_limits: true
    max_velocity: 2.98452
    has_acceleration_limits: false
    max_acceleration: 0
  j1_torso:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  j2:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: false
    max_acceleration: 0
  j2_head:
    has_velocity_limits: true
    max_velocity: 2.98452
    has_acceleration_limits: false
    max_acceleration: 0
  j5:
    has_velocity_limits: true
    max_velocity: 3.1527
    has_acceleration_limits: false
    max_acceleration: 0
  j6:
    has_velocity_limits: true
    max_velocity: 2.98452
    has_acceleration_limits: false
    max_acceleration: 0
  j7:
    has_velocity_limits: true
    max_velocity: 2.98452
    has_acceleration_limits: false
    max_acceleration: 0
  j4:
    has_velocity_limits: true
    max_velocity: 3.1527
    has_acceleration_limits: false
    max_acceleration: 0
  jg2:
    has_velocity_limits: true
    max_velocity: 2.98452
    has_acceleration_limits: false
    max_acceleration: 0