<?xml version="1.0"?>
<robot name="rb1_base" xmlns:xacro="http://www.ros.org/wiki/xacro"> 

  <xacro:include filename="$(find rb1_base_description)/urdf/bases/rb1_base.gazebo.xacro" />

  <xacro:macro name="rb1_base" params="name publish_bf hq">

  <!-- Robot mechanical and motor parameters -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="wheel_width" value="0.175" />

  <!-- BASE FOOTPRINT -->
  <xacro:if value="${publish_bf}">
    <link name="base_footprint">
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
             <box size="0.001 0.001 0.001" />
          </geometry>
      </visual>
    </link>

    <joint name="base_footprint_joint" type="fixed">
       <origin xyz="0 0 ${wheel_radius - wheel_offset_z}" rpy="0 0 0" />
      <parent link="base_footprint"/>
      <child link="base_link" />
    </joint>    
  </xacro:if>

  <!-- BASE_LINK -->
  <link name="base_link">
    <inertial>
      <mass value="25.0" />
      <origin xyz="0 0 0" />
      <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="1.0"  iyz="0.0"  izz="1.0" />
    </inertial>
    <visual>
       <origin xyz="0 0 0" rpy="0 0 0" />
       <xacro:if value="${hq}">
       <geometry>
	     <mesh filename="package://rb1_base_description/meshes/bases/rb1_base_v0.dae"/>
       </geometry>
       </xacro:if>
       <xacro:unless value="${hq}">
       <geometry>
       <mesh filename="package://rb1_base_description/meshes/bases/rb1_base_v0.stl"/>
       </geometry>
       </xacro:unless>
       <material name="darkgrey">
         <color rgba="0.1 0.1 0.1 1"/>
       </material>
    </visual>  
    <collision>
       <origin xyz="0 0 0" rpy="0 0 0 " />
       <geometry>
         <mesh filename="package://rb1_base_description/meshes/bases/rb1_base_v0.dae"/>
       </geometry>
    </collision>
  </link>

  </xacro:macro>
</robot>

