controller_list:
  - name: j2s7s200
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - j2s7s200_joint_1
      - j2s7s200_joint_2
      - j2s7s200_joint_3
      - j2s7s200_joint_4
      - j2s7s200_joint_5
      - j2s7s200_joint_6
      - j2s7s200_joint_7
  - name: j2s7s200_gripper
    action_ns: gripper_command
    type: GripperCommand
    default: true    
    joints:
      - j2s7s200_joint_finger_1
      - j2s7s200_joint_finger_2
  - name: j2s7s200_with_torso
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - torso_slider_joint
      - j2s7s200_joint_1
      - j2s7s200_joint_2
      - j2s7s200_joint_3
      - j2s7s200_joint_4
      - j2s7s200_joint_5
      - j2s7s200_joint_6
      - j2s7s200_joint_7