controller_list:
  - name: fake_j2s7s200_arm_controller
    joints:
      - j2s7s200_joint_1
      - j2s7s200_joint_2
      - j2s7s200_joint_3
      - j2s7s200_joint_4
      - j2s7s200_joint_5
      - j2s7s200_joint_6
      - j2s7s200_joint_7
  - name: fake_j2s7s200_gripper_controller
    joints:
      - j2s7s200_joint_finger_1
      - j2s7s200_joint_finger_2