# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - j2s7s200_joint_1
    - j2s7s200_joint_2
    - j2s7s200_joint_3
    - j2s7s200_joint_4
    - j2s7s200_joint_5
    - j2s7s200_joint_6
    - j2s7s200_joint_7
    - j2s7s200_joint_finger_1
    - j2s7s200_joint_finger_2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: j2s7s200_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j2s7s200_joint_1
      - j2s7s200_joint_2
      - j2s7s200_joint_3
      - j2s7s200_joint_4
      - j2s7s200_joint_5
      - j2s7s200_joint_6
      - j2s7s200_joint_7
  - name: j2s7s200_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j2s7s200_joint_finger_1
      - j2s7s200_joint_finger_2
#  - name: j2s7s200_arm_with_torso_controller
#    action_ns: follow_joint_trajectory
#    default: True
#    type: FollowJointTrajectory
#    joints:
#      - torso_slider_joint
#      - j2s7s200_joint_1
#      - j2s7s200_joint_2
#      - j2s7s200_joint_3
#      - j2s7s200_joint_4
#      - j2s7s200_joint_5
#      - j2s7s200_joint_6
#      - j2s7s200_joint_7
