#rb1_torso:
  j1_torso_controller:
    type: effort_controllers/JointPositionController    
    joint: j1_torso
    pid: {p: 1000.0, i: 1.0, d: 200.0}

  j1_head_controller:
    type: effort_controllers/JointPositionController
    joint: j1_head
    pid: {p: 100.0, i: 0.01, d: 50.0}

  j2_head_controller:
    type: effort_controllers/JointPositionController
    joint: j2_head
    pid: {p: 100.0, i: 0.01, d: 50.0}

#rb1_arm:
  # Mico Arm  
  j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_1
    pid: {p: 350.0, i: 20.0, d: 5.0, i_clamp: 5.0}

  j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_2
    pid: {p: 1500.0, i: 250.0, d: 10.0, i_clamp: 300.0}
  
  j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_3
    pid: {p: 700.0, i: 30, d: 10.0, i_clamp: 30.0}

  j4_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_4
    pid: {p: 500.0, i: 20, d: 10.0, i_clamp: 10.0 }

  j5_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_5
    pid: {p: 500.0, i: 15, d: 10.0, i_clamp: 10.0 }

  jhand_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_6
    pid: {p: 500.0, i: 10, d: 5.0, i_clamp: 5.0 }

  jf1_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_finger_1
    pid: {p: 100.0, i: 0.1, d: 10.0}
    
  jf2_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_finger_2
    pid: {p: 100.0, i: 0.1, d: 10.0}

  jf3_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_finger_3
    pid: {p: 100.0, i: 0.1, d: 10.0}

  mico_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - mico_joint_1
      - mico_joint_2
      - mico_joint_3
      - mico_joint_4
      - mico_joint_5
      - mico_joint_6

    gains: # Required because we're controlling an effort interface

      mico_joint_1: {p: 350, d: 20, i: 5, i_clamp: 5}
      mico_joint_2: {p: 800, d: 30, i: 20, i_clamp: 20}
      mico_joint_3: {p: 700, d: 30, i: 20, i_clamp: 20}
      mico_joint_4: {p: 500, d: 20, i: 10, i_clamp: 10}
      mico_joint_5: {p: 500, d: 15, i: 10, i_clamp: 10}
      mico_joint_6: {p: 500, d: 10, i: 5, i_clamp: 5}


  gripper_controller:
    # Unfortunately this controller type works only for grippers with a single joint :( 
    #type: "effort_controllers/GripperActionController"
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - mico_joint_finger_1
      - mico_joint_finger_2
      - mico_joint_finger_3
    
    gains:
    
      mico_joint_finger_1: {p: 500.0, d: 20, i: 10, i_clamp: 10.0}
      mico_joint_finger_2: {p: 500.0, d: 20, i: 10, i_clamp: 10.0}
      mico_joint_finger_3: {p: 500.0, d: 20, i: 10, i_clamp: 10.0}

