controller_list:
  - name: fake_rb1_arm_controller
    joints:
      - jaco_joint_1
      - jaco_joint_2
      - jaco_joint_3
      - jaco_joint_4
      - jaco_joint_5
      - jaco_joint_6
  - name: fake_rb1_arm_torso_controller
    joints:
      - j1_torso
      - jaco_joint_1
      - jaco_joint_2
      - jaco_joint_3
      - jaco_joint_4
      - jaco_joint_5
      - jaco_joint_6
  - name: fake_rb1_head_controller
    joints:
      - j1_head
      - j2_head
  - name: fake_rb1_robot_controller
    joints:
      - j1_torso
      - j1_head
      - j2_head
      - jaco_joint_1
      - jaco_joint_2
      - jaco_joint_3
      - jaco_joint_4
      - jaco_joint_5
      - jaco_joint_6