controller_list:
  - name: fake_rb1_arm_controller
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      - arm_joint_6
  - name: fake_rb1_torso_controller
    joints:
      - torso_slider_joint
      - head_pan_joint
      - head_tilt_joint
  - name: fake_rb1_head_controller
    joints:
      - head_pan_joint
      - head_tilt_joint
  - name: fake_rb1_arm_torso_controller
    joints:
      - torso_slider_joint
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      - arm_joint_6
  - name: fake_gripper_controller
    joints:
      []
  - name: fake_torso_controller
    joints:
      - torso_slider_joint
  - name: fake_head_controller
    joints:
      - head_tilt_joint